services:
  postgres:
    image: postgres:16
    container_name: bookshelf-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  hasura:
    image: hasura/graphql-engine:v2.40.0.cli-migrations-v3
    container_name: hasura
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
    - .env
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
    volumes:
      - "/home/bugman/Desktop/Project Bookshelf/hasura/migrations:/hasura-migrations"
      - "/home/bugman/Desktop/Project Bookshelf/hasura/metadata:/hasura-metadata"
    restart: unless-stopped

volumes:
  pgdata:
